### ISSUE TITLE
nasm boot/boot.asm -o boot/boot.img process_begin: CreateProcess(NULL, nasm boot/boot.asm -o boot/boot.img, ...) failed. make (e=2): The system cannot find the file specified. mingw32-make.exe: *** [makefile:4: bootloader] Error 2

### ISSUE THREAD

**Issue by rmwvamp** [rmwvamp/graphical-os#1]
**When using the "make" command in WSL or VS Code it shows the same error.** 

nasm boot/boot.asm -o boot/boot.img
```
process_begin: CreateProcess(NULL, nasm boot/boot.asm -o boot/boot.img, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe: *** [makefile:4: bootloader] Error 2
```
![image](https://user-images.githubusercontent.com/34397433/152008614-291d8b03-13f5-414d-b78f-4f89d9760fa7.png)
![image](https://user-images.githubusercontent.com/34397433/152008679-5d283e87-b4f9-4464-a04c-ac9a40403f5a.png)

Also tried deleting all the Environment variables of the System and User. Still showed the same error. 

**Current User Path Variables**
`C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python37-32\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;%USERPROFILE%\.dotnet\tools;C:\MinGW\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\User\AppData\Roaming\npm;`
![image](https://user-images.githubusercontent.com/34397433/152008910-5e8a18ea-cfe6-4b32-9fc2-2c307caa9532.png)

**Current System Path Variables**
`C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\qemu;C:\Program Files\Git\cmd;`
![image](https://user-images.githubusercontent.com/34397433/152009046-1770ca63-74d5-4f3f-9270-83ed346ca489.png)
![image](https://user-images.githubusercontent.com/34397433/152009074-3b74901a-9cb9-4e7b-86ca-eed57f237f95.png)

**MakeFile Includes the following commands**
```
`set path=%path:git\bin=;%
set path=%path:mingw64\bin=;%
set path=%path:usr\bin=;%

all: bootloader

bootloader: 
	nasm boot/boot.asm -o boot/boot.img

clear: 
	rm -f boot/boot.img

run: 
	qemu-system-x86_64.exe -L "C:/Program Files/qemu" -m 64 -fda ./boot/boot.img`

also used 

`set path=%path:git\bin=;%
set path=%path:mingw64\bin=;%
set path=%path:usr\bin=;%

all: bootloader

bootloader: 
	nasm boot/boot.asm -o boot/boot.img

clear: 
	rm -f boot/boot.img

run: 
	qemu-system-x86_64.exe -L "C:/Program Files/qemu" -m 64 -fda ./boot/boot.img`

```
This is the file structure. 
![image](https://user-images.githubusercontent.com/34397433/152009364-6cbfffca-2c4e-421f-98d4-33015413c307.png)

**Comment by vaibhav-anand11** [comment]
### Error Still Persists
**Compiled just the boot.asm file using nasm and worked fine.** 

![image](https://user-images.githubusercontent.com/34397433/152022988-4cd0b880-b920-4897-8a5c-d066e030b445.png)


**Tried making a makefile of another project and it worked there.** 
![image](https://user-images.githubusercontent.com/34397433/152023177-7e3bacd5-0287-47f5-bfdb-b3f25c535880.png)

**Comment by vaibhav-anand11** [comment]
### Resolved, But Make still showing same error in vscode and git bash

Using, WSL installed Build Essential for installing make. All files were missing. 
Command:
`sudo apt-get install build-essential`
![image](https://user-images.githubusercontent.com/34397433/152024841-15b97ef6-a61c-4f89-b954-f257113a22be.png)

For further installation guide, refer the following link.- https://askubuntu.com/questions/161104/how-do-i-install-make

**Comment by vaibhav-anand11** [comment]
Was using powershell on VScode😓😓

Using Ubuntu WSL resolves it. 
![image](https://user-images.githubusercontent.com/34397433/152031218-8b3a777a-89ae-49bc-9053-c83163c72e24.png)
